# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RPPHR.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RPPHR.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRPPHR.proto\"g\n\x0cRedirectData\x12\x13\n\x0bprimary_key\x18\x01 \x01(\t\x12\x17\n\x0flast_visit_time\x18\x02 \x01(\x04\x12)\n\x12redirect_endpoints\x18\x03 \x03(\x0b\x32\r.RedirectStat\"\x8f\x01\n\x0cRedirectStat\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x16\n\x0enumber_of_hits\x18\x02 \x01(\r\x12\x18\n\x10number_of_misses\x18\x03 \x01(\r\x12\x1a\n\x12\x63onsecutive_misses\x18\x04 \x01(\r\x12\x12\n\nurl_scheme\x18\x05 \x01(\t\x12\x10\n\x08url_port\x18\x06 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RPPHR_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REDIRECTDATA']._serialized_start=15
  _globals['_REDIRECTDATA']._serialized_end=118
  _globals['_REDIRECTSTAT']._serialized_start=121
  _globals['_REDIRECTSTAT']._serialized_end=264
# @@protoc_insertion_point(module_scope)
