# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RPPO.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RPPO.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nRPPO.proto\"Q\n\nOriginData\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x17\n\x0flast_visit_time\x18\x02 \x01(\x04\x12\x1c\n\x07origins\x18\x03 \x03(\x0b\x32\x0b.OriginStat\"\xbd\x01\n\nOriginStat\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x16\n\x0enumber_of_hits\x18\x02 \x01(\r\x12\x18\n\x10number_of_misses\x18\x03 \x01(\r\x12\x1a\n\x12\x63onsecutive_misses\x18\x04 \x01(\r\x12\x18\n\x10\x61verage_position\x18\x05 \x01(\x01\x12\x1d\n\x15\x61lways_access_network\x18\x06 \x01(\x08\x12\x18\n\x10\x61\x63\x63\x65ssed_network\x18\x07 \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RPPO_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORIGINDATA']._serialized_start=14
  _globals['_ORIGINDATA']._serialized_end=95
  _globals['_ORIGINSTAT']._serialized_start=98
  _globals['_ORIGINSTAT']._serialized_end=287
# @@protoc_insertion_point(module_scope)
